"""migration001

Revision ID: 7149415b7d72
Revises: 
Create Date: 2025-12-02 23:10:47.673456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7149415b7d72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_tara',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('permisos_modulo', 'modulo',
               existing_type=sa.VARCHAR(length=13, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Enum('CONFIGURACION', 'USUARIOS', 'ROLES', 'MARCACION', 'MOVIMIENTOS', 'AUDITORIA', 'PRODUCCION_LINEAS', 'LINEA_UNO', 'LINEA_DOS', 'LINEA_TRES', 'LINEA_CUATRO', 'LINEA_CINCO', 'LINEA_SEIS', 'CONTROL_TARA', 'CONTROL_PANZA', name='moduloenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permisos_modulo', 'modulo',
               existing_type=sa.Enum('CONFIGURACION', 'USUARIOS', 'ROLES', 'MARCACION', 'MOVIMIENTOS', 'AUDITORIA', 'PRODUCCION_LINEAS', 'LINEA_UNO', 'LINEA_DOS', 'LINEA_TRES', 'LINEA_CUATRO', 'LINEA_CINCO', 'LINEA_SEIS', 'CONTROL_TARA', 'CONTROL_PANZA', name='moduloenum'),
               type_=sa.VARCHAR(length=13, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_table('control_tara')
    # ### end Alembic commands ###
